# Generated by Django 5.0.1 on 2024-01-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_users_temp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="address",
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name="users",
            name="mobile",
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name="users",
            name="name",
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.TextField(max_length=200),
        ),
    ]
