# Generated by Django 5.0.1 on 2024-01-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_users_address_alter_users_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="id",
        ),
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.TextField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
