# Generated by Django 5.0.1 on 2024-06-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Farmers",
            fields=[
                ("name", models.TextField(max_length=200)),
                ("address", models.TextField(max_length=500)),
                ("aadhar", models.TextField(max_length=10)),
                (
                    "mobile",
                    models.TextField(max_length=200, primary_key=True, serialize=False),
                ),
                ("password", models.TextField(max_length=200)),
                ("soiltype", models.TextField(max_length=200)),
                ("previouscrop", models.TextField(max_length=200)),
                ("plannedcrop", models.TextField(max_length=200)),
                ("landarea", models.TextField(max_length=200)),
                ("waterbody", models.TextField(max_length=200)),
                ("district", models.TextField(max_length=200)),
                ("taluk", models.TextField(max_length=200)),
                ("village", models.TextField(max_length=200)),
                ("survey_no", models.TextField(max_length=200)),
            ],
        ),
    ]
