# Generated by Django 5.0.1 on 2024-06-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmers",
            name="aadhar",
            field=models.TextField(max_length=12),
        ),
        migrations.AlterField(
            model_name="farmers",
            name="mobile",
            field=models.TextField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
