# Generated by Django 5.0.1 on 2024-01-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                ("name", models.TextField(max_length=200)),
                ("mobile", models.TextField(max_length=10)),
                ("district", models.TextField(max_length=200)),
                ("taluk", models.TextField(max_length=200)),
                ("village", models.TextField(max_length=200)),
                ("survey_no", models.TextField(max_length=200)),
                ("enquiry_no", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "soil_sample_no",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
            ],
        ),
    ]
