# Generated by Django 5.0.1 on 2024-07-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enquiries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiry",
            name="type",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="district",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="mobile",
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="name",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="survey_no",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="taluk",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="village",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
