# Generated by Django 5.0.1 on 2024-07-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enquiries", "0002_enquiry_type_alter_enquiry_district_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiry",
            name="email",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
